name: CI-CD to Nexus

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-   

      - name: Build with Maven
        run: mvn clean verify

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hola-mundo-jar
          path: target/*.jar

  