name: CI-CD to Nexus

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven
      - name: Build with Maven
        run: mvn clean verify

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hola-mundo-jar
          path: target/*.jar

  deploy:
    name: Deploy to Nexus
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: hola-mundo-jar
          path: downloaded/

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-   

      - name: Deploy JAR to Nexus
        continue-on-error: true
        run: |
          mvn deploy:deploy-file \
            -Durl=${{ secrets.NEXUS_URL }}/repository/releases \
            -DrepositoryId=nexus \
            -Dfile=downloaded/hola-mundo-1.0-SNAPSHOT.jar \
            -DgroupId=com.ejemplo \
            -DartifactId=hola-mundo \
            -Dversion=1.0-SNAPSHOT \
            -Dpackaging=jar \
            -DgeneratePom=true \
            -DpomFile=pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

     