name: CI Maven
on: 
    workflow_dispatch:  
    push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
   
      - name: Cache local Maven repository
        uses: actions/cache@v4

        with:
           path: ~/.m2/repository           
           key: maven-${{ hashFiles('**/pom.xml')}}
           restore-keys: |
              maven-${{ hashFiles('**/pom.xml')}}
              maven-
            
      - run: mvn install


